version: "3"
services:
  load-balance:
    image: nginx:latest
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api-service
    ports:
      - "8080:80"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
  api-service:
    image: ujiik00900/flask-api-service:1.0.0
    deploy:
      mode: replicated
      replicas: 10
      labels: [APP=API]
      placement:
        constraints: [node.role == worker]
networks:
  frontend:
  backend:

volumes:
  db-data: